name: publish-qt-image

on:
    push:
        paths:
            - './src/environment/Dockerfile.qt-image'
            - './.github/workflows/publish-qt-image.yml'
    workflow_dispatch:

jobs:
    publish-qt-docker-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3 

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Build and Push the Qt 6.7.3 Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./src/environment/Dockerfile.qt-image
                push: true
                tags: |
                    ghcr.io/seame-pt/sea-me_team6_2025-26/qt:6.7.3
                    ghcr.io/seame-pt/sea-me_team6_2025-26/qt:latest
                cache-from: type=regitry, ref=ghcr.io/seame-pt/sea-me_team6_2025-26/qt:buildcache
                cache-to: type=regitry, ref=ghcr.io/seame-pt/sea-me_team6_2025-26/qt:buildcache ,mode=max

            - name: Image digest
              run: echo "Image published successfully!"