name: unit-tests

on:
  pull_request:
    branches:
      - testWorkflow

permissions:
  contents: read
  packages: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull test image
        run: docker pull ghcr.io/seame-pt/sea-me_team6_2025-26/seame-tests:latest

      # -----------------------
      # C++ TESTS
      # -----------------------
      - name: Configure + Build + Run C++ tests
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work/src/tests \
            ghcr.io/seame-pt/sea-me_team6_2025-26/seame-tests:latest \
            bash -lc '
              apt-get update && \
              apt-get install -y cmake ninja-build && \
              rm -rf /var/lib/apt/lists/* && \
              rm -rf build && \
              cmake -S . -B build -G Ninja -DENABLE_COVERAGE=ON -DENABLE_PYTHON_TESTS=OFF && \
              cmake --build build && \
              ctest --test-dir build --output-on-failure
            '

      # -----------------------
      # PYTHON TESTS (pytest)
      # -----------------------
      - name: Configure + Run Python tests
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work/src/tests/unit/python \
            ghcr.io/seame-pt/sea-me_team6_2025-26/seame-tests:latest \
            bash -lc '
              apt-get update && \
              apt-get install -y python3 python3-pip && \
              rm -rf /var/lib/apt/lists/* && \
              pip3 install -r requirements.txt && \
              pytest -v --maxfail=1 --disable-warnings
            '

      # -----------------------
      # C++ COVERAGE
      # -----------------------
      - name: Generate C++ coverage HTML
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work/src/tests \
            ghcr.io/seame-pt/sea-me_team6_2025-26/seame-tests:latest \
            bash -lc '
              rm -rf coverage_html coverage.info coverage_filtered.info && \
              lcov --directory build --capture --output-file coverage.info && \
              lcov --remove coverage.info "/usr/*" "*/_deps/*" "*/src/tests/*" "*/inc/*" --output-file coverage_filtered.info && \
              genhtml coverage_filtered.info --output-directory coverage_html
            '

      - name: Upload C++ coverage HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp_coverage_html
          path: src/tests/coverage_html
